### ISSUE TITLE
Can Hedgehog generate functions?

### ISSUE THREAD

**Issue by cmeeren** [hedgehogqa/fsharp-hedgehog#125] opened 2017-10-09 13:54 UTC
A very nice property of FsCheck is that it can generate functions. I can't find this possibility in Hedgehog. Can Hedgehog generate arbitrary functions?

Or is this perhaps fairly easy to implement my own generator for?

**Update:** For future readers, see https://github.com/hedgehogqa/fsharp-hedgehog/issues/125#issuecomment-335418772 and https://github.com/hedgehogqa/fsharp-hedgehog/issues/125#issuecomment-335427591

**Comment by cmeeren** [comment] 2017-10-09 16:36
I have played around a bit and can not find any way to do this. Here's how far I got, which does not work since the `let!` in the inner function is not inside a computation expression.

```f#
  /// Generates a function that, when called, generates a random output value
  /// and returns it. The function will always return the same output value
  /// for the same input value.
  let func<'a,'b when 'a : comparison> (generate:Gen<'b>) : (Gen<'a->'b>) = 
    let mutable rets = Map.empty<'a,'b>
    gen {
      let f = fun x -> 
        match rets.TryFind x with
        | Some ret -> ret
        | None -> 
            let! ret = generate  // Error
            rets <- rets.Add (x, ret)
            ret
      return f
    }
```

**Comment by moodmosaic** [comment] 2017-10-10 07:09
Generators for functions don't exist yet in Hedgehog. See also https://github.com/hedgehogqa/haskell-hedgehog/issues/62.

I think the above example *can* actually compile by always generating a `'b` value, although it's not efficient:

```f#
let func<'a, 'b when 'a : comparison> (g : Gen<'b>) : Gen<'a -> 'b> = 
    let kvs =
        Map.empty<'a, 'b>
    gen {
        let! v = g
        let fn =
            fun k -> 
                match kvs.TryFind k with
                | Some v -> v
                | None   -> kvs.Add (k, v) |> ignore; v
        return fn
    }
```

**Comment by cmeeren** [comment] 2017-10-10 07:15
Your example doesn't seem to update `kvs` (`Map.Add` returns a new map).

**Comment by moodmosaic** [comment] 2017-10-10 07:19
Ugh. I should have wrote that I typed the above code on a text-editor 😮 I've now updated it but still don't have a proper IDE or code-editor to try it.

**Comment by cmeeren** [comment] 2017-10-10 07:22
I haven't looked closely at the output, but it compiles and the first test I tried it in ran successfully. For the record, here's my version (renamed values and changed indenting):

```f#
  /// Generates a function that, when called, generates a random output value
  /// using the supplied generator and returns it. The function will always
  /// return the same output value for the same input value.
  let func<'a, 'b when 'a : comparison> generate = 
    let mutable retVals = Map.empty<'a, 'b>
    gen {
      let! retVal = generate
      let fn =
        fun inp -> 
          match retVals.TryFind inp with
          | Some v -> v
          | None -> retVals <- retVals.Add (inp, retVal); retVal
      return fn
    }
```

**Comment by moodmosaic** [comment] 2017-10-10 07:23
👍

**Comment by cmeeren** [comment] 2017-10-10 08:55
The generator doesn't seem to work properly. For any given test run, the generated function returns the same single value regardless of input.

**Comment by moodmosaic** [comment] 2017-10-10 09:00
Can you show the example you tried? (If it's a small one and can be easily reproduced, it'll help.)

**Comment by cmeeren** [comment] 2017-10-10 09:06
To reproduce:

```f#
Property.check <| property {
  let! xs = ... // generate a list of integers (say, 10 elements long)
  let! f = Gen.func (Gen.unicode)  // unicode is just an example
  return true  // break debugger here
}
```

Break on the indicated line in VS and inspect `f`. Observe that the `Map` contains the same return value for all inputs.

**Comment by cmeeren** [comment] 2017-10-10 09:09
A more automated test:

```f#
Property.check <| property {
  let! xs = ... // generate a list of integers (say, 10 elements long)
  let! f = Gen.func (Gen.unicode)  // unicode is just an example
  let grouped = xs |> List.groupBy f
  return List.Length = 1
}
```

The above property should generally not pass.

**Comment by moodmosaic** [comment] 2017-10-10 09:30
Ugh, of course, since `let! retVal = generate` is outside of the function that's being returned... 😯

**Comment by cmeeren** [comment] 2017-10-10 09:37
Perhaps something like this? Will test.

```f#
/// Generates a list of values and a function that maps those particular
/// values to other values. The input and output values are generated
/// using the supplied generators, and the list is exponentially scaled
/// between the given lower and upper limits. The returned function throws
/// if called with an item that is not in the returned list.
let listAndFunc inpGen outGen lower upper =
  gen {
    let! inpList = inpGen |> Gen.list (Range.exponential lower upper)
    let! outList = outGen |> Gen.list (Range.singleton inpList.Length)
    let inOutMap = List.zip inpList outList |> Map.ofList
    return inpList, (fun inp -> inOutMap.Item inp)
  }
```

**Comment by moodmosaic** [comment] 2017-10-10 09:38
Perhaps something like [this](https://github.com/hedgehogqa/haskell-hedgehog/issues/62#issuecomment-299609517), too.

**Comment by jystic** [comment] 2017-10-10 09:40
@cmeeren I think that's close, I would try to generate the pair of key/value together, so something like:
```fsharp
let listAndFunc inpGen outGen lower upper =
  gen {
    let! list = Gen.list (Range.exponential lower upper) (Gen.zip inpGen outGen)
    let inOutMap = Map.ofList list
    return inpList, (fun inp -> inOutMap.Item inp)
  }
```

**Comment by cmeeren** [comment] 2017-10-10 09:41
@moodmosaic  I don't really read Haskell, but to me that seems fundamentally to what I suggested.

@jystic Thanks! I didn't know about Gen.zip.

**Comment by moodmosaic** [comment] 2017-10-10 09:42
@cmeeren, yes, indeed 🎉

**Comment by cmeeren** [comment] 2017-10-10 09:47
I tested the latest suggestion now, and it seems to work brilliantly.

**Comment by cmeeren** [comment] 2017-10-10 10:16
Two alternative APIs:

```f#
/// Generates a list using inpGen together with a function that maps each of
/// the elements in the list to values generated by outGen. The returned
/// function throws if called with an item that is not in the returned list.
let withMapTo (outGen:Gen<'b>) (inpGen:Gen<'a list>) =
  gen {
    let! inputs = inpGen
    let! outputs = outGen |> Gen.list (Range.singleton inputs.Length)
    let inOutMap = List.zip inputs outputs |> Map.ofList
    return inputs, (fun inp -> inOutMap.Item inp)
  }

/// Generates a function that maps a list of inputs to output values generated
/// by outGen. The returned function throws if called with an item that is
/// not in the input list.
let mapperTo outGen (inputs:'a list) =
  gen {
    let! outputs = outGen |> Gen.list (Range.singleton inputs.Length)
    let inOutMap = List.zip inputs outputs |> Map.ofList
    return fun inp -> inOutMap.Item inp
  }
```

Usages of all three:

```f#
let! xs, f = Gen.listAndFunc Gen.ascii Gen.bool 1 100

let! xs, f = Gen.ascii |> Gen.list (Range.exponential 1 100) |> Gen.withMapTo (Gen.bool)

let! xs = Gen.ascii |> Gen.list (Range.exponential 1 100)
let! f = xs |> Gen.mapperTo (Gen.bool)
```

**Comment by moodmosaic** [comment] 2017-11-13 09:11
Closing this, as we're going to tackle it in https://github.com/hedgehogqa/fsharp-hedgehog-experimental/issues/5.

**Closed by moodmosaic** 2017-11-13 09:11 UTC
Labels: enhancement

**Comment by tonymorris** [comment] 2018-11-20 01:22
Feel free to port.

https://hackage.haskell.org/package/hedgehog-fn
