### ISSUE TITLE
A way of generating a smart diff?

### ISSUE THREAD

**Issue by AlexeyRaga** [hedgehogqa/fsharp-hedgehog#325] opened 2021-03-22 05:06 UTC
`Hedgehog` in Haskell is awesome at generating smart diff when using `===` operator:

![image](https://user-images.githubusercontent.com/1394391/111942872-5ec73b80-8b28-11eb-8828-51d4c5ff97f4.png)

Is there a way of doing it in F#, too?

**Comment by TysonMN** [comment] 2021-03-22 12:25
Duplicate of #211

**Closed** 2021-03-22 23:22 UTC
