### ISSUE TITLE
generator does not generate values in range

### ISSUE THREAD

**Issue by snuup** [hedgehogqa/fsharp-hedgehog#218] opened 2020-09-28 21:50 UTC
Gen.int (Range.linear 10 1000) |> Gen.printSample

create these values:

    === Outcome ===
    55
    === Shrinks ===
    10
    33
    44
    50
    53
    54
    .
    === Outcome ===
    27
    === Shrinks ===
    10
    19
    23
    25
    26
    .
    === Outcome ===
    55
    === Shrinks ===
    10
    33
    44
    50
    53
    54
    .
    === Outcome ===
    51
    === Shrinks ===
    10
    31
    41
    46
    49
    50
    .
    === Outcome ===
    63
    === Shrinks ===
    10
    37
    50
    57
    60
    62
    .
    val it : unit = ()
    
    > 

what does Range.linear mean? I would expect values being in the range 10 .. 1000 in the example above.

I understand that when using 

    Gen.int r |> Gen.sample 100 3

I see larger values:

    val it : List<int> = [897; 716; 634]

This should be documented. When using a normal test with 100 runs a size of 100 is never reached. So it is unexpected to me that a range of 10..1000 hardly rarely reaches the large values.

**Comment by moodmosaic** [comment] 2020-09-30 03:31
FWIW, this week I'm travelling but I should be able to get to this during weekend, the earliest. Perhaps @jacobstanley can take a look in the meantime.

**Comment by moodmosaic** [comment] 2020-10-30 22:17
@snuup, this is caused by `printSample` which uses a fixed size (of 10, IIRC) and a fix count (10/2, IIRC).

On range I'd suggest to look at @jacobstanley's explanation in https://youtu.be/AIv_9T0xKEo?t=1236. In your case `linear` means that as the size increases the range moves towards `1000` and shrinks to the lower bound which is `10`.

**Comment by moodmosaic** [comment] 2020-10-30 22:20
Closing this as we cover the support for docs in #118. Feel free to reopen and/or keep the discussion going if needed.

**Closed by moodmosaic** 2020-10-30 22:20 UTC
Labels: question
