### ISSUE TITLE
Automated derivation of record types, discriminated unions, tuples, enums

### ISSUE THREAD

**Issue by ditadi** [hedgehogqa/fsharp-hedgehog#101] opened 2017-05-23 16:57 UTC
FsCheck uses reflection to derive default implementations of various F# types as per [1].  After quick look hedgehog doesn't seem to have this functionality (if not so, please let me know).  Should this functionality  added and how high of a priority should it be?

> Furthermore, by using reflection, FsCheck can derive default implementations of record types, discriminated unions, tuples, enums and basic classes in terms of any primitive types that are defined (either in FsCheck or by you).

[1] [FsCheckDocs](https://fscheck.github.io/FsCheck/TestData.html#Useful-methods-on-the-Arb-module])

**Comment by moodmosaic** [comment] 2017-05-23 17:07
There are at least two different ways you can do this, as discussed also in https://github.com/hedgehogqa/fsharp-hedgehog/issues/93.

---

This item is a duplicate of https://github.com/hedgehogqa/fsharp-hedgehog/issues/93/, so I'm going to close it. We may continue the discussion in https://github.com/hedgehogqa/fsharp-hedgehog/issues/93, and even reopen that one if needed.

**Closed by moodmosaic** 2017-05-23 17:07 UTC
