### ISSUE TITLE
F# 5 applicative computation expression

### ISSUE THREAD

**Issue by adam-becker** [hedgehogqa/fsharp-hedgehog#268] opened 2021-01-13 16:21 UTC
With F# 5 on the horizon, I think we should consider adding support for the new applicative computation expressions therein. This is mostly a tracking issue so we don't forget. Brief notes on this are [here][applicative].

[applicative]: https://devblogs.microsoft.com/dotnet/announcing-f-5/#applicative-computation-expressions

**Comment by TysonMN** [comment] 2021-01-13 16:41
Is this a duplicate of #267?

**Comment by TysonMN** [comment] 2021-03-03 14:08
For which of our monadic types is its monadic behavior different from its application behavior?  I do not know of any but I could be missing something.

**Comment by TysonMN** [comment] 2021-09-05 15:56
Oh, I realized how the applicative behavior would differ from the monadic behavior.

Hedgehog currently shrinks "multiple" generators sequentially.  This is required for the monadic behavior. The applicative behavior could be different; it could for example, cyclically shrink the generators until no improvement is possible (i.e. a Pareto optimal position).

I find this very interesting.

**Comment by TysonMN** [comment] 2021-09-05 15:58
@moodmosaic, does Haskell Hedgehog have this applicative behavior?

**Comment by moodmosaic** [comment] 2021-09-07 13:43
>cyclically shrink the generators until no improvement is possible

That should be possible according to @edsko's [article](https://well-typed.com/blog/2019/05/integrated-shrinking/#example-generating-pairs) (which is _the_ reference). Though I don't have ghci in front me.

**Comment by adam-becker** [comment] 2021-09-07 20:50
I was thinking of how this could differ, especially wrt `apply`'s implied behavior of being the "parallel" equivalent to `bind`'s "sequential" behavior. Perhaps all of the applied parameters receive the same seed and grow together? Unless that's what was already mentioned.

That would be an interesting way to control the integrated shrinking behavior of Hedgehog.

**Comment by TysonMN** [comment] 2021-09-07 22:41
My intuition is that the applicative behavior of `Random<>` should match its monadic behavior.

 > Perhaps all of the applied parameters receive the same seed [...]

I don't think that would be a good idea. Then applicatively generating a list would produce a list with the same value throughout.

> [...] and grow together?

I don't know what you mean by "grow".

**Closed** 2022-01-01 01:17 UTC
Labels: enhancement

**Comment by TysonMN** [comment] 2022-01-01 01:25
This is included in [version 0.12.1](https://www.nuget.org/packages/Hedgehog/0.12.1).
